version: 2
jobs:
  build:
    branches:
      only:
        - circleci
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Working directory
          command: pwd && ls -l
      - run:
          name: download terraform
          command: apt-get update -y && apt-get install wget unzip -y && wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip && unzip terraform_0.11.8_linux_amd64.zip && chmod +x terraform
      - run:
          name: Terraform init
          command: ./terraform init
      - run:
          name: Terraform plan and apply
          command: ./terraform plan && ./terraform apply --auto-approve=true
