version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Working directory
          command: pwd && ls -l
      - run:
          name: download terraform
          command: sudo apt-get update -y && sudo apt-get install wget && wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip && unzip terraform_0.11.8_linux_amd64.zip && chmod +x terraform
      - run:
          name: run terraform
          command: terraform init